command: ["streamlit", "run", "app.py", "--server.port", "8080", "--server.address", "0.0.0.0", "--server.headless", "true"]
env:
  - name: DATABRICKS_HOST
    valueFrom:
      resourceKey: databricks-host
  - name: DATABRICKS_TOKEN
    valueFrom:
      resourceKey: databricks-token
  - name: JOB_ID
    valueFrom:
      resourceKey: job-id
  - name: HTTP_PATH
    valueFrom:
      resourceKey: http-path
  - name: DASHBOARD_URL
    valueFrom:
      resourceKey: dashboard-url