command: ['streamlit', 'run', 'app.py']
env:
  - name: STREAMLIT_GATHER_USAGE_STATS
    value: 'false'
  - name: DATABRICKS_HOST
    valueFrom: DATABRICKS_HOST
  - name: DATABRICKS_TOKEN
    valueFrom: DATABRICKS_TOKEN
  - name: JOB_ID
    valueFrom: JOB_ID
  - name: HTTP_PATH
    valueFrom: HTTP_PATH
  - name: DASHBOARD_URL
    valueFrom: DASHBOARD_URL