command: ["streamlit", "run", "app.py", "--server.port", "8080", "--server.address", "0.0.0.0", "--server.headless", "true", "--server.enableCORS", "false", "--server.enableXsrfProtection", "false"]
env:
  - name: STREAMLIT_GATHER_USAGE_STATS
    value: "false"
  - name: DATABRICKS_HOST
    value: {{secrets/app-scope/DATABRICKS_HOST}}
  - name: DATABRICKS_TOKEN
    value: {{secrets/app-scope/DATABRICKS_TOKEN}}
  - name: JOB_ID
    value: {{secrets/app-scope/JOB_ID}}
  - name: HTTP_PATH
    value: {{secrets/app-scope/HTTP_PATH}}
  - name: DASHBOARD_URL
    value: {{secrets/app-scope/DASHBOARD_URL}}