DATABRICKS_HOST = "<YOUR DATABRICKS HOST NAME>"
DATABRICKS_TOKEN = "<YOUR DATABRICKS TOKEN>"
JOB_ID = "<YOUR DATABRICKS PIPELINE JOB ID>"
HTTP_PATH = "<YOUR DATABRICKS HTTP PATH>"
DASHBOARD_URL = "<YOUR DATABRICKS DASHBOARD URL>"
